# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pretext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(choices=[('EU4', 'Europa Universalis IV'), ('HOI4', 'Hearts of Iron 4'), ('OFF', 'Other')], max_length=10),
        ),
    ]
