# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_subscriptions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
