# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_auto_20171107_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='parent',
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='comment.ArticleComment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='target_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comment', to='comment.ArticleComment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
