# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0010_auto_20171108_1256'),
        ('article', '0006_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.SmallIntegerField(default=0)),
                ('dislikes', models.SmallIntegerField(default=0)),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.ArticleComment')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='like_counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='like.LikeCounter'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
